"""Weekly share card: a 1200x630 PNG the page advertises as its og:image.
Regenerated by the refresh cron; skipped gracefully when Pillow is absent."""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "site", "card.png")


def build(data):
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        return False
    W, H = 1200, 630
    img = Image.new("RGB", (W, H), "#ffffff")
    d = ImageDraw.Draw(img)

    def font(size, bold=False):
        for name in (["Menlo.ttc", "DejaVuSansMono-Bold.ttf"] if bold else ["Menlo.ttc", "DejaVuSansMono.ttf"]):
            try:
                return ImageFont.truetype(name, size)
            except OSError:
                continue
        return ImageFont.load_default(size)

    d.rectangle([0, 0, W, 10], fill="#15803d")
    d.text((60, 60), "SOCIAL SIMULATION ARENA", font=font(44, True), fill="#111110")
    d.text((60, 120), "Can AI predict what the public will think next week?", font=font(26), fill="#55554f")
    entries = ((data.get("backtest") or {}).get("overall") or [])[:5]
    y = 210
    for i, e in enumerate(entries):
        sk = e["mean_skill"] * 100
        txt = f"{i+1}  {e['entrant']:<14} {'+' if sk > 0 else ''}{sk:.1f}%"
        color = "#0a6a30" if sk > 0 else ("#96948d" if abs(sk) < 0.05 else "#4f4e49")
        d.text((60, y), txt, font=font(34, i == 0), fill=color)
        y += 62
    d.text((60, 560), f"{(data.get('backtest') or {}).get('n_rounds', 0)} real releases · live season from Aug 11 · cjj.li/social-sim-arena",
           font=font(22), fill="#96948d")
    img.save(OUT)
    return True
